Models/DTO/ChangePassword.cs
using System.ComponentModel.DataAnnotations;

namespace PlantNest.Models.DTO
{
    public class ChangePasswordModel
    {
        [Required]
        public string ? CurrentPassword { get; set; }

        [Required]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*[#$^+=!*()@%&]).{6,}$",ErrorMessage ="Minimum length 6 and must contain  1 Uppercase,1 lowercase, 1 special character and 1 digit")]
        public string? NewPassword { get; set; }
        [Required]
        [Compare("NewPassword")]
        public string ? PasswordConfirm { get; set; }
        
    }
}

Models/DTO/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace PlantNest.Models.DTO
{
    public class LoginModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Models/DTO/RegistrationModel.cs
using System.ComponentModel.DataAnnotations;

namespace PlantNest.Models.DTO
{
    public class RegistrationModel
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*[#$^+=!*()@%&]).{6,}$",ErrorMessage ="Minimum length 6 and must contain  1 Uppercase,1 lowercase, 1 special character and 1 digit")]
        public string Password { get; set; }
        [Required]
        [Compare("Password")]
        public string PasswordConfirm { get; set; }
        public string? Role { get; set; }
        
    }
}

Models/DTO/Status.cs
namespace PlantNest.Models.DTO
{
    public class Status
    {
        public int StatusCode { get; set; }
        public string Message { get; set; }
    }
}

Models/Domain/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace PlantNest.Models.Domain
{
    public class ApplicationUser:IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string? ProfilePicture { get; set; }
    }
}

Models/Domain/DatabaseContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace PlantNest.Models.Domain
{
    public class DatabaseContext : IdentityDbContext<ApplicationUser>
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options)
        {

        }
       


    }
}

Models/ErrorViewModel.cs
namespace PlantNest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PlantNest.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        public IActionResult Display()
        {
            return View();
        }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PlantNest.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Display()
        {
            Console.WriteLine(User.IsInRole("admin"));
            return View();
        }
    }
}

Controllers/HomeController.cs
using PlantNest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace PlantNest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

Controllers/UserAuthenticationController.cs
using PlantNest.Models.DTO;
using PlantNest.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using PlantNest.Models.Domain;

namespace PlantNest.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private readonly IUserAuthenticationService _authService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserAuthenticationController(
            IUserAuthenticationService authService,
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager)
        {
            this._authService = authService;
            this._signInManager = signInManager;
            this._userManager = userManager;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _authService.LoginAsync(model);

                if (user != null)
                {
                    var user1 = await _userManager.FindByNameAsync(model.Username);
                    var result = await _signInManager.CheckPasswordSignInAsync(user1, model.Password, lockoutOnFailure: false);

                    if (result.Succeeded)
                    {
                        if (await _userManager.IsInRoleAsync(user1, "admin"))
                        {
                            return RedirectToAction("Display", "Admin");
                        }
                        else if (await _userManager.IsInRoleAsync(user1, "user"))
                        {
                            return RedirectToAction("Display", "Dashboard");
                        }
                    }
                }


                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View(model);
            }

            return View(model);
        }


        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationModel model)
        {
            if(!ModelState.IsValid) { return View(model); }
            model.Role = "user";
            var result = await this._authService.RegisterAsync(model);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await this._authService.LogoutAsync();  
            return RedirectToAction(nameof(Login));
        }
        [AllowAnonymous]
        public async Task<IActionResult> RegisterAdmin()
        {
            RegistrationModel model = new RegistrationModel
            {
                Username = "admin",
                Email = "admin@gmail.com",
                FirstName = "John",
                LastName = "Doe",
                Password = "Admin@12345#"
            };
            model.Role = "admin";
            var result = await this._authService.RegisterAsync(model);
            return Ok(result);
        }

        [Authorize]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult>ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
              return View(model);
            var result = await _authService.ChangePasswordAsync(model, User.Identity.Name);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(ChangePassword));
        }

    }
}

Views/Admin/Display.cshtml
@{
    Layout = null;
}
<div>
    I am admin page
</div>
<a href="@Url.Action("Logout","UserAuthentication")">Logout</a>

Views/Dashboard/Display.cshtml
@{
    string username = User.Identity.Name;
    Layout = null;
}
<div>
   
    welcome @username
</div>
<a href="@Url.Action("Logout","UserAuthentication")">Logout</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dotnet6MvcLogin</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Dot net 6 authentication</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li><a href="/Dashboard/Display">Dashboard</a></li>
                @if (User.IsInRole("admin"))
                {
                    <li><a href="/Admin/Display">Admin Page</a></li>
                }
                @if (!string.IsNullOrEmpty(User.Identity.Name))
                {
                    <li><a href="/UserAuthentication/ChangePassword">ChangePassword</a></li>
                    <li><a href="/UserAuthentication/Logout">Logout</a></li>
                }
            </ul>
        </div>
    </nav>


    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

Views/UserAuthentication/ChangePassword.cshtml
@model PlantNest.Models.DTO.ChangePasswordModel

<div class="container">
    <div class="row">
        <div class="col-md-6 center-block">
            <h3>Registration</h3>
            <form asp-action="ChangePassword" method="post">
                <div class="form-group">
                    <label>Current Password*</label>
                    <input type="password" class="form-control" asp-for="CurrentPassword"/>
                    <span class="text-danger" asp-validation-for="CurrentPassword"></span>
                </div>

                <div class="form-group">
                    <label>New Password*</label>
                    <input type="password" class="form-control" asp-for="NewPassword" />
                    <span class="text-danger" asp-validation-for="NewPassword"></span>
                </div>

                <div class="form-group">
                    <label>Confirm New Password*</label>
                    <input type="password" class="form-control" asp-for="PasswordConfirm" />
                    <span class="text-danger" asp-validation-for="PasswordConfirm"></span>

                </div>
                
                @if (TempData["msg"] != null)
                {
                    <div class="form-group">
                       <span class="text-info">@TempData["msg"]</span>
                    </div>
                }

                <button type="submit" class="btn btn-info">Save</button>
            </form>
        </div>
    </div>
</div>

Views/UserAuthentication/Login.cshtml
@model PlantNest.Models.DTO.LoginModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
	<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <style>

    .main{
            background-image: url('../Images/background.jpg');

        }
        .login{
            margin-top:10%;
            margin-bottom: auto;
        }
form {
  /*border: 3px solid #f1f1f1;*/
  width:40%;
  margin-left:auto;
  margin-right:auto;
  margin-top:10px;
            background: rgba(0,0,0,0.4);
            backdrop-filter: saturate(100%) blur(5px);
  padding: 20px;
  color:#fff;
}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: green;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

.container {
  padding: 16px;
}
.heading{
    color: #fff;
}
.msg{
  padding: 0px;
}


.err{
    color:red;
}
</style>
 
</head>
<body class="main">

    <div class="login">
        <h1 class="text-center heading">Plant Nest</h1>
        <form asp-action="Login" method="post">

            <div class="container-fluid">
                <label asp-for="Username"><b>Username</b></label>
                <input class="form-control" type="text" asp-for="Username" placeholder="Enter Username">
                <div class="msg">
                    <span class="err" asp-validation-for="Username"></span>
                </div>



                <label asp-for="Password"><b>Password</b></label>
                <input class="form-control" type="password" asp-for="Password" placeholder="Enter Password">
                <div class="msg">
                    <span asp-validation-for="Password" class="err"></span>
                </div>


                @if (TempData["msg"] != null)
                {
                    <div class="msg">@TempData["msg"]</div>
                }

                <button type="submit">Login</button>
                <a class="text-alert" href="/UserAuthentication/Registration">Not a user? Signup</a>
            </div>
        </form>
    </div>
        
</body>
</html>

Views/UserAuthentication/Registration.cshtml
@model PlantNest.Models.DTO.RegistrationModel
@{
    Layout = null;
}

<link href="/css/bootstrap.min.css" rel="stylesheet" />
<style>

    body {
        background-image: url('../Images/background.jpg');
    }

    .login {
        margin-top: 10%;
        margin-bottom: auto;
    }

    form {
        /*border: 3px solid #f1f1f1;*/
        width: 40%;
        margin-left: auto;
        margin-right: auto;
        margin-top: 10px;
        background: rgba(0,0,0,0.4);
        backdrop-filter: saturate(100%) blur(5px);
        padding: 40px;
        color: #fff;
        border-radius:10px;
    }

    input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    button {
        background-color: green;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
    }

    .container {
        padding: 16px;
    }

    .heading {
        color: #fff;
    }

    .msg {
        padding: 0px;
    }


    .err {
        color: red;
    }
</style>
@Html.ValidationSummary()
<div class="container">
    <div class="row">
        <div class="center-block">
            <h3 class="text-center text-uppercase heading">Registration</h3>
            <form asp-action="Registration" method="post">
                <div class="form-group">
                    <label>FName*</label>
                    <input type="text" class="form-control" asp-for="FirstName"/>
                    <span class="text-danger"  asp-validation-for="FirstName"></span>
                </div>

                <div class="form-group">
                    <label>LName*</label>
                    <input type="text" class="form-control" asp-for="LastName" />
                    <span class="text-danger" asp-validation-for="LastName"></span>
                </div>

                <div class="form-group">
                    <label>Email</label>
                    <input type="text" class="form-control" asp-for="Email" />
                    <span class="text-danger" asp-validation-for="Email"></span>

                </div>

                <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" asp-for="Username" />
                    <span class="text-danger" asp-validation-for="Username"></span>

                </div>

                <div class="form-group">
                    <label>Password (eg. John@123)</label>
                    <input type="password" class="form-control" asp-for="Password" />
                    <span class="text-danger" asp-validation-for="Password"></span>

                </div>

                <div class="form-group">
                    <label>Password confirm</label>
                    <input type="password" class="form-control" asp-for="PasswordConfirm" />
                    <span class="text-danger" asp-validation-for="PasswordConfirm"></span>

                </div>

               
                
                @if (TempData["msg"] != null)
                {
                    <div class="form-group">
                       <span class="text-info">@TempData["msg"]</span>
                    </div>
                }

                <button type="submit" class="btn btn-info">Registration</button>
                <a class="text-alert" href="/UserAuthentication/Login">Already Registered? Login</a>
            </form>
        </div>
    </div>
</div>